### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by hellobartekk** [ranajahanzaib/firebase-rest-api-template#1]
Server responds with Cannot GET /

Tried running on firebase as well as locally. Both return the same error.

Live firebase project
https://us-central1-hhpp-563dd.cloudfunctions.net/api

Testing using Postman
<img width="1011" alt="Screenshot 2021-11-15 at 20 19 26" src="https://user-images.githubusercontent.com/73197423/141848320-36536a6e-4a04-4432-a147-ea267a32dfe9.png">

Any suggestions? Thank you

**Comment by ranajahanzaib** [comment]
## Edit
So, I tried with commenting `main.use("/v1", app);`, and it did NOT work. If you've removed/commented this line, I'd suggest adding it back. In order to drop the "/v1" prefix, you could do it as;

```js
main.use(app); // No "/v1"
```

I'm sure it would resolve the issue. If you're still facing the issue, feel free to let me know. I'd be happy to help.

-------

## Original
Thanks so much, @hellobartekk for creating an issue here.

I've used this template for multiple projects to deploy Cloud Functions on Firebase that act as REST APIs, and all of them are working fine. Let's find out why it's not working for you and what we could do to make it work for you.

Would you be able to share code from your `index.js`, `.firebaserc`, and `firebase.json` files with me? Alternatively, you could temporarily add me as a collaborator on the project as long as there's no trouble. I'd be more than happy to help you debug the issue.

I wasn't too sure if the template would work right now, because of [this change](https://github.com/ranajahanzaib/firebase-rest-api-template/commit/620955f76b6f463540c550473911abebec35c1bb) that I believe I made after using this template. So, I went ahead tried to deploy this template on a fresh Firebase project. In my case, it worked.

However, I learned that using `firebase deploy` inside the `api/` folder doesn't work. For some reason, it's returning `HTTP Error: 403, Unknown Error`. Below is the console output:

```
rj@ubuntu-11900:~/apis/firebase-rest-api-template/api$ firebase deploy

=== Deploying to 'fb-rest-api-template'...

i  deploying firestore, functions, hosting
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing api directory for uploading...
i  functions: packaged api (35.83 KB) for uploading
i  firestore: latest version of firestore.rules already up to date, skipping upload...
✔  firestore: deployed indexes in firestore.indexes.json successfully
⚠  functions: Upload Error: HTTP Error: 403, Unknown Error

Error: HTTP Error: 403, Unknown Error

   ╭──────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                  │
   │                         Update available 9.12.0 → 9.22.0                         │
   │   To update to the latest version using npm, run npm install -g firebase-tools   │
   │          For other CLI management options, visit the CLI documentation           │
   │                                                                                  │
   │                                                                                  │
   │                                                                                  │
   ╰──────────────────────────────────────────────────────────────────────────────────╯


Having trouble? Try firebase [command] --help
```
As we can see, in my case, the deployment of the function failed. @hellobartekk, you don't have to worry about this, because your function is successfully deployed. But this is something, I wanted to mention in case you or someone else use the `firebase deploy` inside the `api` directory. It won't work, especially with `firebase-tools@9.12.0`.

I'm still using `firebase-tools v9.12.0`. I wanted to retry a couple of times before upgrading it.

Then, I tried `firebase deploy` from the parent folder, and it worked. The Cloud Function is now deployed. You can now access it from either https://fb-rest-api-template.web.app/v1/timestamp or https://us-central1-fb-rest-api-template.cloudfunctions.net/api/v1/timestamp

```
rj@ubuntu-11900:~/apis/firebase-rest-api-template$ firebase deploy

=== Deploying to 'fb-rest-api-template'...

i  deploying firestore, functions, hosting
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing api directory for uploading...
i  functions: packaged api (35.83 KB) for uploading
i  firestore: latest version of firestore.rules already up to date, skipping upload...
✔  firestore: deployed indexes in firestore.indexes.json successfully
✔  functions: api folder uploaded successfully
i  hosting[fb-rest-api-template]: beginning deploy...
i  hosting[fb-rest-api-template]: found 1 files in public
✔  hosting[fb-rest-api-template]: file upload complete
✔  firestore: released rules firestore.rules to cloud.firestore
i  functions: creating Node.js 12 function api(us-central1)...
✔  functions[api(us-central1)]: Successful create operation. 
i  hosting[fb-rest-api-template]: finalizing version...
✔  hosting[fb-rest-api-template]: version finalized
i  hosting[fb-rest-api-template]: releasing new version...
✔  hosting[fb-rest-api-template]: release complete

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/fb-rest-api-template/overview
Hosting URL: https://fb-rest-api-template.web.app
```
From: https://fb-rest-api-template.web.app/v1/timestamp
<center>
<img src='https://fb-rest-api-template.web.app/img/1637021354238.png' >
</center>

From: https://us-central1-fb-rest-api-template.cloudfunctions.net/api/v1/timestamp
<center>
<img src='https://fb-rest-api-template.web.app/img/1637021392047.png' >
</center>

**Comment by ranajahanzaib** [comment]
Thanks again, @hellobartekk for creating the issue. I believe it's now addressed in [8c18a49](https://github.com/ranajahanzaib/firebase-rest-api-template/commit/8c18a493448a7ef64b7a8bebfd95fdf3019ff248) update. 

**Fixes**:
https://github.com/ranajahanzaib/firebase-rest-api-template/blob/9330362803501db95e069f000b761666a66d38da/api/index.js#L8

**Comment by hellobartekk** [comment]
Worked like a charm! Thank you very much @ranajahanzaib for looking into this.

**Comment by ranajahanzaib** [comment]
Perfect! I'm glad it worked on your end. Thanks again for letting me know about this.
